# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b01f713104fa396948cb74768900b322f21e84b725e4976cc8b3a072acc44cff56784f0a338998b3a8d9d641f72735044a8d2da6bcd1bbc2c38681a4aeb24939

test:
  secret_key_base: 21c01039876396d232dd04e19075a8128318f0ac8fb0cbfb346a53568331bfdfbd4e563b9ffde1bb60b80ad615410a79956171ad73c2ddcb56dc9679fe8d7b46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
